CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Match IDENTITY strategy
    name VARCHAR(50) NOT NULL,
    age BIGINT NOT NULL
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    pages BIGINT NOT NULL,
    author VARCHAR(50) NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users(id) -- Reference users.id
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    students BIGINT NOT NULL,
    location VARCHAR(50) NOT NULL
);

-- Many-to-Many Join Tables
CREATE TABLE course_and_user (
    user_id BIGINT NOT NULL REFERENCES users(id),
    course_id BIGINT NOT NULL REFERENCES courses(id),
    PRIMARY KEY (user_id, course_id)
);

CREATE TABLE university_and_user (
    user_id BIGINT NOT NULL REFERENCES users(id),
    university_id BIGINT NOT NULL REFERENCES universities(id),
    PRIMARY KEY (user_id, university_id)
);

CREATE TABLE outbox
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value TEXT NOT NULL
);